// Restored MVP content, not recovered original activities. General education only.
const themes = [
  "Hydration",
  "Movement",
  "Mindfulness",
  "Sleep",
  "Nutrition",
  "Breathwork",
  "Digital Detox",
  "Gratitude",
  "Purpose",
];
const activities = [
  [
    "Notice when you feel thirsty.",
    "Place drinking water somewhere convenient.",
    "Choose a cup you enjoy using.",
    "Have water with a meal if comfortable.",
    "Check that your drinking water is safe.",
    "Plan water access for an outing.",
    "Notice which drinks you enjoy without judging yourself.",
    "Follow any fluid limits given by your care team.",
    "Reflect on one hydration habit to keep.",
  ],
  [
    "Notice how your body feels before moving.",
    "Choose a comfortable movement you enjoy.",
    "Try a short gentle walk or seated movement if suitable.",
    "Take a comfortable break from sitting if able.",
    "Make space for safe movement at home.",
    "Move at a pace that feels easy.",
    "Rest when your body asks for it.",
    "Stop if you feel pain, dizziness or breathing difficulty.",
    "Reflect on a movement you would like to repeat.",
  ],
  [
    "Notice three things you can see.",
    "Listen to a sound around you.",
    "Feel the support of your chair or floor.",
    "Pause before one everyday task.",
    "Name an emotion without judging it.",
    "Notice a thought and let it pass.",
    "Bring attention to a comfortable sensation.",
    "Try a quiet moment with your eyes open.",
    "Reflect on whether the pause felt useful.",
  ],
  [
    "Notice your usual bedtime.",
    "Choose a realistic wind-down cue.",
    "Make your sleeping space comfortable where possible.",
    "Set aside a worry to revisit tomorrow.",
    "Try a calming activity before bed.",
    "Notice how evening screens affect your routine.",
    "Plan a consistent waking time that fits your life.",
    "Note persistent sleep concerns to discuss with a professional.",
    "Choose one restful habit to continue.",
  ],
  [
    "Notice hunger and fullness without judging them.",
    "Plan a regular meal that fits your day.",
    "Add a food you enjoy to a meal.",
    "Explore an affordable fruit or vegetable if suitable.",
    "Include a familiar source of protein if suitable.",
    "Check food storage and hygiene.",
    "Eat at a comfortable pace when possible.",
    "Respect allergies and your care team's nutrition advice.",
    "Reflect on a satisfying meal without counting calories.",
  ],
  [
    "Sit in a comfortable supported position.",
    "Notice your breathing without changing it.",
    "Relax your shoulders if comfortable.",
    "Let your breath stay gentle and unforced.",
    "Try a brief quiet pause with normal breathing.",
    "Avoid holding your breath or breathing rapidly.",
    "Return to ordinary activity if uncomfortable.",
    "Stop if you feel dizzy, faint or short of breath.",
    "Reflect on whether gentle awareness helped.",
  ],
  [
    "Notice when you reach for your phone automatically.",
    "Choose one nonessential notification to mute.",
    "Place your phone aside during a short activity.",
    "Choose a screen-free activity you enjoy.",
    "Keep important support and emergency contacts available.",
    "Set a small boundary that fits your responsibilities.",
    "Notice how a short screen break feels.",
    "Make room for an in-person conversation if welcome.",
    "Reflect on a digital habit you want to keep.",
  ],
  [
    "Notice one small thing you appreciated today.",
    "Write a kind sentence to yourself.",
    "Remember a supportive person.",
    "Acknowledge an effort you made.",
    "Notice something pleasant in your surroundings.",
    "Thank someone if it feels comfortable.",
    "Allow difficult feelings alongside appreciation.",
    "Recall a moment of comfort.",
    "Choose an appreciation practice that feels natural.",
  ],
  [
    "Name a value that matters to you.",
    "Recall an activity that feels meaningful.",
    "Notice a strength you used today.",
    "Choose one small achievable next step.",
    "Consider a person or community you care about.",
    "Make room for rest as part of your plans.",
    "Write a flexible intention for tomorrow.",
    "Review which journey habits fit your life.",
    "Celebrate exploring the journey at your own pace.",
  ],
];
export const CHALLENGE_DAYS = themes.map((theme, i) => ({
  day: i + 1,
  theme,
  pillar: "A small everyday practice",
  tip: "Adapt each activity to your circumstances. You can pause or skip activities. Follow your care team's advice for health limitations.",
  tasks: activities[i],
}));
