import { defineConfig, mergeConfig, type Plugin } from "vite";
import base from "../vite.config.ts";
import { fileURLToPath, URL } from "node:url";
import { allowed, callLocal, prepare } from "./backend";
import { createReadiness } from "./readiness";
const origin = "http://127.0.0.1:5175";
function testingApi(): Plugin {
  const readiness = createReadiness(prepare, async () => {
    const user = await callLocal("users:getCurrentUser");
    if (!user) throw new Error("LOCAL_BACKEND_UNAVAILABLE");
  });
  return {
    name: "local-synthetic-testing",
    apply: "serve",
    configureServer(server) {
      void readiness.check(); // Errors are sanitized; later requests retry initialization.
      server.middlewares.use(async (req, res, next) => {
        if (!req.url?.startsWith("/_testing/")) return next();
        res.setHeader("Content-Type", "application/json");
        res.setHeader("Cache-Control", "no-store");
        const send = (status: number, value: unknown) => {
          res.statusCode = status;
          res.end(JSON.stringify(value));
        };
        if (req.headers.host !== "127.0.0.1:5175") return send(403, { error: "INVALID_ORIGIN" });
        if (req.method === "GET" && req.url === "/_testing/health")
          return send(200, { application: "vitality9-synthetic", ready: await readiness.check() });
        if (
          req.method !== "POST" ||
          req.headers.origin !== origin ||
          req.headers["content-type"] !== "application/json"
        )
          return send(403, { error: "INVALID_ORIGIN" });
        try {
          let raw = "";
          for await (const chunk of req) {
            raw += chunk.toString();
            if (raw.length > 20000) return send(413, { error: "INVALID_INPUT" });
          }
          const { name, args } = JSON.parse(raw);
          if (!allowed.has(name)) return send(403, { error: "FORBIDDEN" });
          if (!(await readiness.check())) throw new Error("LOCAL_BACKEND_UNAVAILABLE");
          let result;
          try {
            result = await callLocal(name, args);
          } catch (error) {
            if (error instanceof Error && error.message === "LOCAL_BACKEND_UNAVAILABLE")
              readiness.invalidate();
            if (
              name !== "aiCoach:chat" ||
              !(error instanceof Error) ||
              error.message !== "NOT_CONFIGURED"
            )
              throw error;
            const { coach } = await server.ssrLoadModule("/convex/lib/coach.ts");
            result = await coach(args, async () => {
              const message = String(args.message).toLowerCase();
              const replies = [
                [
                  /sleep|bed|rest/,
                  "For Sleep, choose a realistic wind-down cue and a comfortable waking time. What part of your sleep routine would you like to work on?",
                ],
                [
                  /water|hydrat/,
                  "For Hydration, keep safe drinking water somewhere convenient and notice thirst. Follow any fluid limits from your care team.",
                ],
                [
                  /mov|walk|exercise/,
                  "For Movement, what injuries or limitations should we consider? If suitable, choose a short comfortable walk or seated movement. Stop if pain, dizziness or breathing difficulty occurs.",
                ],
                [
                  /breath/,
                  "For Breathwork, sit comfortably and notice normal, unforced breathing for a brief pause. Do not hold your breath or force its pace. Stop if dizzy or uncomfortable.",
                ],
                [
                  /gratitude|thank/,
                  "For Gratitude, notice one small thing you appreciated today. Difficult feelings can exist alongside appreciation.",
                ],
                [
                  /nutrition|food|eat/,
                  "For Nutrition, consider a regular meal using familiar foods you enjoy. Respect allergies and your care team's advice.",
                ],
                [
                  /purpose|goal/,
                  "For Purpose, name a value that matters to you and choose one small achievable next step.",
                ],
                [
                  /phone|digital|screen/,
                  "For Digital Detox, try a short break from a nonessential screen activity while keeping support contacts available.",
                ],
              ] as const;
              const advice =
                replies.find(([pattern]) => pattern.test(message))?.[1] ??
                "For Mindfulness, pause and notice three things around you. Which of the nine pillars would you like to explore?";
              return "Offline practice response — not generated by Gemini.\n\n" + advice;
            });
          }
          send(200, { result });
        } catch (error) {
          const message = error instanceof Error ? error.message : "";
          const code = /^[A-Z_]+$/.test(message) ? message : "LOCAL_BACKEND_UNAVAILABLE";
          send(400, { error: code });
        }
      });
    },
  };
}
export default mergeConfig(
  base,
  defineConfig({
    plugins: [testingApi()],
    server: {
      host: "127.0.0.1",
      port: 5175,
      strictPort: true,
      allowedHosts: ["127.0.0.1"],
      cors: false,
      fs: {
        deny: [
          "**/.env*",
          "**/.git/**",
          "**/.convex/**",
          "**/convex/lib/**",
          "**/testing/backend.ts",
        ],
      },
    },
    resolve: {
      alias: [
        {
          find: "convex/react",
          replacement: fileURLToPath(new URL("./convex.tsx", import.meta.url)),
        },
        {
          find: "@usehercules/auth/react",
          replacement: fileURLToPath(new URL("./auth.ts", import.meta.url)),
        },
      ],
    },
  }),
);
